### ISSUE TITLE
Request: Would you consider adding a license to this repository?

### ISSUE THREAD

**Issue by griever989** [cbrgm/cmangos-docker#2]
Hi there!

This project looks very useful. I would really love to use it as a base for getting cmangos running in docker. Would you consider adding a license to it so others are allowed to use it?

In case you wanted a resource on what some licenses you could use: https://choosealicense.com/

**Comment by cbrgm** [comment]
Hey, sorry for my late reply. I'll do that

**Comment by cbrgm** [comment]
Merged
